package constants

const (
	TYPE_FAST_PAY    = "FastPay"
	TYPE_SESSION_PAY = "SessionPay"

	STATUS_SUCCESS = 1
	STATUS_FAIL    = 0
	STATUS_PENDING = 2
	STATUS_CANCEL  = 3
	STATUS_REFUND  = 4
	STATUS_REJECT  = 5
	STATUS_PAY     = 6
	STATUS_PAYED   = 7

	STATE_SUCCESS = 1
	STATE_FAIL    = 0
	STATE_PENDING = 2
	STATE_CANCEL  = 3
	STATE_REFUND  = 4
	STATE_REJECT  = 5
	STATE_PAY     = 6
	STATE_PAYED   = 7

	REASON_SUCCESS = 1
	REASON_FAIL    = 0
	REASON_PENDING = 2
	REASON_CANCEL  = 3
	REASON_REFUND  = 4
	REASON_REJECT  = 5
	REASON_PAY     = 6
	REASON_PAYED   = 7
	REASON_TIMEOUT = 8
)
